# Generated by Django 4.1.3 on 2022-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Sorm',
            },
        ),
    ]
